### ISSUE TITLE
Code failing at stage2_missing_table1_all

### ISSUE THREAD

**Issue by venexia** [opensafely/post-covid-mentalhealth#22]
When I was developing the code for PR https://github.com/opensafely/post-covid-mentalhealth/pull/20, the pipeline was failing at the action 'stage2_missing_table1_all'. Please can we investigate.

**Comment by kurttaylor** [comment]
Just checked this and it is due to there being no “active” column in the active analyses table on your branch. It was there on previous branches, so must’ve been accidentally deleted

**Comment by venexia** [comment]
That column isn't needed anymore but even when I fixed that, this wouldn't run for me.
