### ISSUE TITLE
make_model_output possible mistake

### ISSUE THREAD

**Issue by marwaalarab** [opensafely/post-covid-mentalhealth#56]
I think N_total needs to be N_exposed ? 
https://github.com/opensafely/post-covid-mentalhealth/blob/main/analysis/model/make_model_output.R#:~:text=%3D%20TRUE)%2C-,min_exposed%20%3D%20min(N_total%2C%20na.rm%20%3D%20TRUE)%2C,-min_events%20%3D%20min

**Comment by venexia** [comment]
@marwaalarab - on which line in this file? N_total should refer to everyone in the analysis (exposed and unexposed) and N_exposed is a subset of this.

**Comment by venexia** [comment]
Oh, I think I have spotted it on [line 91](https://github.com/opensafely/post-covid-mentalhealth/blob/91c7d7967fe7e1ee8dd49b1995f5dcd4f22f7af4/analysis/model/make_model_output.R#L91)?

**Comment by marwaalarab** [comment]
Yes! sorry I thought I pasted a link with the line highlighted but it seems it doesn't work here.
